version = 0.1

[default.deploy.parameters]
stack_name = "sam-snowscrape-app"
resolve_s3 = true
s3_prefix = "sam-snowscrape-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-west-2"
